export const APP_INIT = 'APP_INIT';
export const APP_SECRET_ERROR = 'APP_SECRET_ERROR';
export const APP_SECRET_FETCH = 'APP_SECRET_FETCH';
export const APP_SECRET_SET = 'APP_SECRET_SET';

export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_FETCH = 'USER_LOGIN_FETCH';
export const USER_LOGIN_SET = 'USER_LOGIN_SET';
