export const APP_INIT = 'APP_INIT';
export const APP_SECRET_ERROR = 'APP_SECRET_ERROR';
export const APP_SECRET_FETCH = 'APP_SECRET_FETCH';
export const APP_SECRET_SET = 'APP_SECRET_SET';

export const EVENT_ENTRY_ERROR = 'EVENT_ENTRY_ERROR';
export const EVENT_ENTRY_FETCH = 'EVENT_ENTRY_FETCH';
export const EVENT_ENTRY_SET = 'EVENT_ENTRY_SET';
export const EVENT_LIST_FETCH = 'EVENT_LIST_FETCH';
export const EVENT_LIST_SET = 'EVENT_LIST_SET';

export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_FETCH = 'USER_LOGIN_FETCH';
export const USER_LOGIN_OUT = 'USER_LOGIN_OUT';
export const USER_LOGIN_REMOVE = 'USER_LOGIN_REMOVE';
export const USER_LOGIN_SET = 'USER_LOGIN_SET';
export const USER_TOKEN_FETCH = 'USER_TOKEN_FETCH';
